name: relnet-cenv
channels:
  - defaults
dependencies:
  - scipy=1.2.0
  - networkx=2.2
  - numpy=1.16.3
  - numpy-base=1.16.3
  - pandas=0.23.4
  - python=3.6.8
  - scikit-learn=0.20.3
  - seaborn=0.9.0
  - psutil=5.6.1
  - pymongo=3.7.2
  - pip
  - pip:
      - pytest==5.4.1
      - tensorflow==1.13.1
      - ipykernel==5.1.2
      - xxhash==1.3.0
      - cachetools==3.1.0
      - objsize==0.3.2
      - multiprocess==0.70.7
      - celery==4.4.2
      - flower==0.9.3
      - dataclasses==0.6
      - tqdm==4.39.0
      - matplotlib==3.1.3
      - pytest==5.4.1
      - pygraphviz==1.5
      - network2tikz==0.1.8
      - Jinja2==2.11.1